global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'forsen_ai_api'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'app'
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'ingest'
